version: '3.5'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    # volumes:
      # - .env:/usr/src/bachelor-backend/.env
      # - /usr/src/bachelor-backend/static/profile
      # - /usr/src/bachelor-backend/storage
    ports:
      - 8081:8081
    environment: 
      - spring.datasource.url=jdbc:mysql://db:3306/learning
      - spring.datasource.username=root
      - spring.datasource.password=12345678
      - server.port=8081
      - spring.mail.host=host.docker.internal
      - spring.mail.port=1025
      #spring.mail.username=<login user to smtp server>
      #spring.mail.password=<login password to smtp server>
      - spring.mail.properties.mail.smtp.auth=false
      - spring.mail.properties.mail.smtp.starttls.enable=true

  db:
    image: mysql
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: learning
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  default:
    name: learning
